"""add_user_api_keys

Revision ID: d247c5a3c226
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 22:34:25.578764
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd247c5a3c226'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
